import yfinance as yf
import pandas as pd
import numpy as np
import telebot
import os

# --- CONFIGURATION ---
# Replace with your actual Channel/User ID and Bot Token
TOKEN =  os.getenv("TELEGRAM_TOKEN")
CHANNEL_ID = os.getenv("TELEGRAM_CHAT_ID")  # or your numeric channel ID

bot = telebot.TeleBot(TOKEN)

# A sample list of Indian Stock Tickers (Nifty)
TICKERS = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "BHARTIARTL.NS", "SBIN.NS", "LTIM.NS", "ITC.NS", "TATAMOTORS.NS"
]

def calculate_rsi(series, period=14):
    """Standard Relative Strength Index Calculation"""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    
    rs = gain / (loss + 1e-9)  # Prevent division by zero
    rsi = 100 - (100 / (1 + rs))
    return rsi

def get_market_data(ticker_symbol):
    """Downloads historical data and safely extracts metrics handling Multi-Index variations"""
    try:
        # Download a small historical window (1mo gives enough data to compute 14-period RSI safely)
        df = yf.download(ticker_symbol, period="1mo", interval="1d", progress=False)
        
        if df.empty or len(df) < 15:
            print(f"⚠️ Insufficient or empty data for {ticker_symbol}")
            return None
            
        # --- THE MULTI-INDEX FIX ---
        # Modern yfinance returns columns like ('Close', 'RELIANCE.NS') instead of just 'Close'.
        # This line flattens it down to level 0 ('Close'), which restores compatibility with standard syntax.
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
            
        # Compute technical metrics
        df['RSI'] = calculate_rsi(df['Close'])
        
        # Pull values out via position indexing (iloc) to shield against timestamp index issues
        latest_row = df.iloc[-1]
        previous_row = df.iloc[-2]
        
        close_price = float(latest_row['Close'])
        prev_close = float(previous_row['Close'])
        rsi_val = float(latest_row['RSI'])
        
        # Percent Change math
        pct_change = ((close_price - prev_close) / prev_close) * 100
        
        return {
            "ticker": ticker_symbol.replace(".NS", ""),
            "close": round(close_price, 2),
            "change": round(pct_change, 2),
            "rsi": round(rsi_val, 2) if not np.isnan(rsi_val) else None
        }
    except Exception as e:
        print(f"❌ Core processing error on {ticker_symbol}: {e}")
        return None

def generate_daily_report():
    compiled_metrics = []
    
    print("⏳ Processing index lists...")
    for ticker in TICKERS:
        data = get_market_data(ticker)
        if data:
            compiled_metrics.append(data)
            
    if not compiled_metrics:
        print("❌ Analytical pool is empty. Aborting broadcast.")
        return
        
    # Sort assets based on performance movements
    sorted_assets = sorted(compiled_metrics, key=lambda x: x['change'], reverse=True)
    
    gainers = sorted_assets[:3]                 # Top 3 Gainers
    losers = sorted_assets[-3:][::-1]           # Top 3 Losers (sorted lowest to highest)
    
    # Filter out Oversold/Overbought targets via RSI limits
    rsi_watchlist = [a for a in compiled_metrics if a['rsi'] and (a['rsi'] >= 70 or a['rsi'] <= 30)]

    # --- STRING COMPOSITION BLOCKS ---
    # Fetch today's target date dynamically
    report_date = pd.Timestamp.now().strftime('%d %b %Y')
    
    message = f"🟢 <b>QuantPulse News | Daily Brief</b>\n📅 <code>{report_date}</code>\n"
    message += "━━━━━━━━━━━━━━━━━━\n\n"
    
    # 📈 Top Gainers Section
    message += "📈 <b>TOP GAINERS</b>\n"
    for stock in gainers:
        message += f"• <b>{stock['ticker']}</b>: ₹{stock['close']} (<code>+{stock['change']}%</code>)\n"
    message += "\n"
    
    # 📉 Top Losers Section
    message += "📉 <b>TOP LOSERS</b>\n"
    for stock in losers:
        message += f"• <b>{stock['ticker']}</b>: ₹{stock['close']} (<code>{stock['change']}%</code>)\n"
    message += "\n"
    
    # 🔍 RSI Watchlist Section
    message += "🔍 <b>RSI WATCHLIST</b>\n"
    if rsi_watchlist:
        for stock in rsi_watchlist:
            condition = "⚠️ OVERBOUGHT" if stock['rsi'] >= 70 else "🛒 OVERSOLD"
            message += f"• <b>{stock['ticker']}</b>: RSI {stock['rsi']} | {condition}\n"
    else:
        message += "• No anomalous indicators found today.\n"
        
    message += "\n━━━━━━━━━━━━━━━━━━\n"
    message += "<i>Generated by QuantPulse AI Engine</i>"

    # Send the final compiled summary to the channel
    try:
        bot.send_message(CHANNEL_ID, message, parse_mode="HTML")
        print("🚀 Market Brief dispatched successfully!")
    except Exception as e:
        print(f"Telegram execution error: {e}")

if __name__ == "__main__":
    generate_daily_report()
