name: QuantPulse Auto-Run
on:
  schedule:
    # Market Close Report (4:15 PM IST)
    - cron: '45 10 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # UPGRADED VERSION

      - name: Install dependencies
        run: pip install requests yfinance pandas pandas-ta

      - name: Execute Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python quantpulse.py
